/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AdaptiveImmuneFirewallInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BLOCK_STAKE_THRESHOLD"
      | "WARN_STAKE_THRESHOLD"
      | "challengeBondMultiplierBp"
      | "challengeThreat"
      | "challengeWindow"
      | "emergencyPause"
      | "emergencyUnpause"
      | "getDispute"
      | "getThreatIntel"
      | "immunityScoreBp"
      | "intuitionVault"
      | "isBlocked"
      | "minBond"
      | "minRegistrationAssets"
      | "owner"
      | "paused"
      | "registerThreat"
      | "renounceOwnership"
      | "requireCounterTripleExists"
      | "resolveThreat"
      | "riskScore"
      | "setChallengeBondMultiplierBp"
      | "setChallengeWindow"
      | "setMinBond"
      | "setMinRegistrationAssets"
      | "setRequireCounterTripleExists"
      | "setThresholds"
      | "setTreasury"
      | "setWinnerRewardBp"
      | "threats"
      | "transferOwnership"
      | "treasury"
      | "volatilityExtension"
      | "volatilityExtensionEnabled"
      | "volatilityThresholdBp"
      | "winnerRewardBp"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChallengeWindowExtended"
      | "EmergencyPaused"
      | "EmergencyUnpaused"
      | "OwnershipTransferred"
      | "Paused"
      | "ThreatChallenged"
      | "ThreatRegistered"
      | "ThreatResolved"
      | "ThresholdsEvaluated"
      | "ThresholdsUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BLOCK_STAKE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WARN_STAKE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengeBondMultiplierBp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengeThreat",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDispute",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getThreatIntel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "immunityScoreBp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "intuitionVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "minBond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minRegistrationAssets",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerThreat",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requireCounterTripleExists",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveThreat",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setChallengeBondMultiplierBp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChallengeWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinRegistrationAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequireCounterTripleExists",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setThresholds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWinnerRewardBp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "threats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "volatilityExtension",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "volatilityExtensionEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "volatilityThresholdBp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winnerRewardBp",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BLOCK_STAKE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WARN_STAKE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeBondMultiplierBp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeThreat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getThreatIntel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "immunityScoreBp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "intuitionVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBlocked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minRegistrationAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerThreat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireCounterTripleExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveThreat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "riskScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setChallengeBondMultiplierBp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChallengeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMinBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinRegistrationAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequireCounterTripleExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWinnerRewardBp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "volatilityExtension",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "volatilityExtensionEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "volatilityThresholdBp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winnerRewardBp",
    data: BytesLike
  ): Result;
}

export namespace ChallengeWindowExtendedEvent {
  export type InputTuple = [
    suspect: AddressLike,
    oldDeadline: BigNumberish,
    newDeadline: BigNumberish,
    netStart: BigNumberish,
    netEnd: BigNumberish
  ];
  export type OutputTuple = [
    suspect: string,
    oldDeadline: bigint,
    newDeadline: bigint,
    netStart: bigint,
    netEnd: bigint
  ];
  export interface OutputObject {
    suspect: string;
    oldDeadline: bigint;
    newDeadline: bigint;
    netStart: bigint;
    netEnd: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPausedEvent {
  export type InputTuple = [admin: AddressLike];
  export type OutputTuple = [admin: string];
  export interface OutputObject {
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyUnpausedEvent {
  export type InputTuple = [admin: AddressLike];
  export type OutputTuple = [admin: string];
  export interface OutputObject {
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThreatChallengedEvent {
  export type InputTuple = [
    suspect: AddressLike,
    challenger: AddressLike,
    counterTripleId: BigNumberish,
    bond: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    suspect: string,
    challenger: string,
    counterTripleId: bigint,
    bond: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    suspect: string;
    challenger: string;
    counterTripleId: bigint;
    bond: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThreatRegisteredEvent {
  export type InputTuple = [
    suspect: AddressLike,
    tripleId: BigNumberish,
    registrar: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    suspect: string,
    tripleId: bigint,
    registrar: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    suspect: string;
    tripleId: bigint;
    registrar: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThreatResolvedEvent {
  export type InputTuple = [
    suspect: AddressLike,
    confirmed: boolean,
    winnerPayout: BigNumberish,
    treasuryCut: BigNumberish
  ];
  export type OutputTuple = [
    suspect: string,
    confirmed: boolean,
    winnerPayout: bigint,
    treasuryCut: bigint
  ];
  export interface OutputObject {
    suspect: string;
    confirmed: boolean;
    winnerPayout: bigint;
    treasuryCut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsEvaluatedEvent {
  export type InputTuple = [
    target: AddressLike,
    tripleId: BigNumberish,
    assets: BigNumberish,
    status: BigNumberish
  ];
  export type OutputTuple = [
    target: string,
    tripleId: bigint,
    assets: bigint,
    status: bigint
  ];
  export interface OutputObject {
    target: string;
    tripleId: bigint;
    assets: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsUpdatedEvent {
  export type InputTuple = [newWarn: BigNumberish, newBlock: BigNumberish];
  export type OutputTuple = [newWarn: bigint, newBlock: bigint];
  export interface OutputObject {
    newWarn: bigint;
    newBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AdaptiveImmuneFirewall extends BaseContract {
  connect(runner?: ContractRunner | null): AdaptiveImmuneFirewall;
  waitForDeployment(): Promise<this>;

  interface: AdaptiveImmuneFirewallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BLOCK_STAKE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  WARN_STAKE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  challengeBondMultiplierBp: TypedContractMethod<[], [bigint], "view">;

  challengeThreat: TypedContractMethod<
    [_suspect: AddressLike, _counterTripleId: BigNumberish],
    [void],
    "payable"
  >;

  challengeWindow: TypedContractMethod<[], [bigint], "view">;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  emergencyUnpause: TypedContractMethod<[], [void], "nonpayable">;

  getDispute: TypedContractMethod<
    [_target: AddressLike],
    [
      [bigint, string, bigint, bigint, bigint] & {
        challengeDeadline: bigint;
        challenger: string;
        counterTripleId: bigint;
        registrarBond: bigint;
        challengerBond: bigint;
      }
    ],
    "view"
  >;

  getThreatIntel: TypedContractMethod<
    [_target: AddressLike],
    [
      [bigint, bigint, string, bigint, bigint, bigint] & {
        tripleId: bigint;
        registeredAt: bigint;
        registrar: string;
        conviction: bigint;
        counterConviction: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  immunityScoreBp: TypedContractMethod<
    [_target: AddressLike],
    [bigint],
    "view"
  >;

  intuitionVault: TypedContractMethod<[], [string], "view">;

  isBlocked: TypedContractMethod<[_target: AddressLike], [boolean], "view">;

  minBond: TypedContractMethod<[], [bigint], "view">;

  minRegistrationAssets: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerThreat: TypedContractMethod<
    [_suspect: AddressLike, _tripleId: BigNumberish],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requireCounterTripleExists: TypedContractMethod<[], [boolean], "view">;

  resolveThreat: TypedContractMethod<
    [_suspect: AddressLike],
    [void],
    "nonpayable"
  >;

  riskScore: TypedContractMethod<
    [_target: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        assets: bigint;
        shares: bigint;
        status: bigint;
        tripleId: bigint;
      }
    ],
    "view"
  >;

  setChallengeBondMultiplierBp: TypedContractMethod<
    [_bp: BigNumberish],
    [void],
    "nonpayable"
  >;

  setChallengeWindow: TypedContractMethod<
    [_seconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinBond: TypedContractMethod<
    [_minBond: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinRegistrationAssets: TypedContractMethod<
    [_newMin: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRequireCounterTripleExists: TypedContractMethod<
    [_require: boolean],
    [void],
    "nonpayable"
  >;

  setThresholds: TypedContractMethod<
    [_newWarn: BigNumberish, _newBlock: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setWinnerRewardBp: TypedContractMethod<
    [_bp: BigNumberish],
    [void],
    "nonpayable"
  >;

  threats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        tripleId: bigint;
        registeredAt: bigint;
        registrar: string;
        bond: bigint;
        challengeDeadline: bigint;
        challenger: string;
        counterTripleId: bigint;
        challengerBond: bigint;
        assetsStart: bigint;
        counterAssetsStart: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  volatilityExtension: TypedContractMethod<[], [bigint], "view">;

  volatilityExtensionEnabled: TypedContractMethod<[], [boolean], "view">;

  volatilityThresholdBp: TypedContractMethod<[], [bigint], "view">;

  winnerRewardBp: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BLOCK_STAKE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WARN_STAKE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengeBondMultiplierBp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengeThreat"
  ): TypedContractMethod<
    [_suspect: AddressLike, _counterTripleId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "challengeWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyUnpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [_target: AddressLike],
    [
      [bigint, string, bigint, bigint, bigint] & {
        challengeDeadline: bigint;
        challenger: string;
        counterTripleId: bigint;
        registrarBond: bigint;
        challengerBond: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getThreatIntel"
  ): TypedContractMethod<
    [_target: AddressLike],
    [
      [bigint, bigint, string, bigint, bigint, bigint] & {
        tripleId: bigint;
        registeredAt: bigint;
        registrar: string;
        conviction: bigint;
        counterConviction: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "immunityScoreBp"
  ): TypedContractMethod<[_target: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "intuitionVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isBlocked"
  ): TypedContractMethod<[_target: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "minBond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minRegistrationAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerThreat"
  ): TypedContractMethod<
    [_suspect: AddressLike, _tripleId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requireCounterTripleExists"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "resolveThreat"
  ): TypedContractMethod<[_suspect: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskScore"
  ): TypedContractMethod<
    [_target: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        assets: bigint;
        shares: bigint;
        status: bigint;
        tripleId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setChallengeBondMultiplierBp"
  ): TypedContractMethod<[_bp: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setChallengeWindow"
  ): TypedContractMethod<[_seconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinBond"
  ): TypedContractMethod<[_minBond: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinRegistrationAssets"
  ): TypedContractMethod<[_newMin: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRequireCounterTripleExists"
  ): TypedContractMethod<[_require: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setThresholds"
  ): TypedContractMethod<
    [_newWarn: BigNumberish, _newBlock: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWinnerRewardBp"
  ): TypedContractMethod<[_bp: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "threats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        tripleId: bigint;
        registeredAt: bigint;
        registrar: string;
        bond: bigint;
        challengeDeadline: bigint;
        challenger: string;
        counterTripleId: bigint;
        challengerBond: bigint;
        assetsStart: bigint;
        counterAssetsStart: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "volatilityExtension"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "volatilityExtensionEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "volatilityThresholdBp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "winnerRewardBp"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ChallengeWindowExtended"
  ): TypedContractEvent<
    ChallengeWindowExtendedEvent.InputTuple,
    ChallengeWindowExtendedEvent.OutputTuple,
    ChallengeWindowExtendedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPaused"
  ): TypedContractEvent<
    EmergencyPausedEvent.InputTuple,
    EmergencyPausedEvent.OutputTuple,
    EmergencyPausedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyUnpaused"
  ): TypedContractEvent<
    EmergencyUnpausedEvent.InputTuple,
    EmergencyUnpausedEvent.OutputTuple,
    EmergencyUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ThreatChallenged"
  ): TypedContractEvent<
    ThreatChallengedEvent.InputTuple,
    ThreatChallengedEvent.OutputTuple,
    ThreatChallengedEvent.OutputObject
  >;
  getEvent(
    key: "ThreatRegistered"
  ): TypedContractEvent<
    ThreatRegisteredEvent.InputTuple,
    ThreatRegisteredEvent.OutputTuple,
    ThreatRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ThreatResolved"
  ): TypedContractEvent<
    ThreatResolvedEvent.InputTuple,
    ThreatResolvedEvent.OutputTuple,
    ThreatResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsEvaluated"
  ): TypedContractEvent<
    ThresholdsEvaluatedEvent.InputTuple,
    ThresholdsEvaluatedEvent.OutputTuple,
    ThresholdsEvaluatedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsUpdated"
  ): TypedContractEvent<
    ThresholdsUpdatedEvent.InputTuple,
    ThresholdsUpdatedEvent.OutputTuple,
    ThresholdsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ChallengeWindowExtended(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ChallengeWindowExtendedEvent.InputTuple,
      ChallengeWindowExtendedEvent.OutputTuple,
      ChallengeWindowExtendedEvent.OutputObject
    >;
    ChallengeWindowExtended: TypedContractEvent<
      ChallengeWindowExtendedEvent.InputTuple,
      ChallengeWindowExtendedEvent.OutputTuple,
      ChallengeWindowExtendedEvent.OutputObject
    >;

    "EmergencyPaused(address)": TypedContractEvent<
      EmergencyPausedEvent.InputTuple,
      EmergencyPausedEvent.OutputTuple,
      EmergencyPausedEvent.OutputObject
    >;
    EmergencyPaused: TypedContractEvent<
      EmergencyPausedEvent.InputTuple,
      EmergencyPausedEvent.OutputTuple,
      EmergencyPausedEvent.OutputObject
    >;

    "EmergencyUnpaused(address)": TypedContractEvent<
      EmergencyUnpausedEvent.InputTuple,
      EmergencyUnpausedEvent.OutputTuple,
      EmergencyUnpausedEvent.OutputObject
    >;
    EmergencyUnpaused: TypedContractEvent<
      EmergencyUnpausedEvent.InputTuple,
      EmergencyUnpausedEvent.OutputTuple,
      EmergencyUnpausedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ThreatChallenged(address,address,uint256,uint256,uint256)": TypedContractEvent<
      ThreatChallengedEvent.InputTuple,
      ThreatChallengedEvent.OutputTuple,
      ThreatChallengedEvent.OutputObject
    >;
    ThreatChallenged: TypedContractEvent<
      ThreatChallengedEvent.InputTuple,
      ThreatChallengedEvent.OutputTuple,
      ThreatChallengedEvent.OutputObject
    >;

    "ThreatRegistered(address,uint256,address,uint256)": TypedContractEvent<
      ThreatRegisteredEvent.InputTuple,
      ThreatRegisteredEvent.OutputTuple,
      ThreatRegisteredEvent.OutputObject
    >;
    ThreatRegistered: TypedContractEvent<
      ThreatRegisteredEvent.InputTuple,
      ThreatRegisteredEvent.OutputTuple,
      ThreatRegisteredEvent.OutputObject
    >;

    "ThreatResolved(address,bool,uint256,uint256)": TypedContractEvent<
      ThreatResolvedEvent.InputTuple,
      ThreatResolvedEvent.OutputTuple,
      ThreatResolvedEvent.OutputObject
    >;
    ThreatResolved: TypedContractEvent<
      ThreatResolvedEvent.InputTuple,
      ThreatResolvedEvent.OutputTuple,
      ThreatResolvedEvent.OutputObject
    >;

    "ThresholdsEvaluated(address,uint256,uint256,uint8)": TypedContractEvent<
      ThresholdsEvaluatedEvent.InputTuple,
      ThresholdsEvaluatedEvent.OutputTuple,
      ThresholdsEvaluatedEvent.OutputObject
    >;
    ThresholdsEvaluated: TypedContractEvent<
      ThresholdsEvaluatedEvent.InputTuple,
      ThresholdsEvaluatedEvent.OutputTuple,
      ThresholdsEvaluatedEvent.OutputObject
    >;

    "ThresholdsUpdated(uint256,uint256)": TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
    ThresholdsUpdated: TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
