/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ImmuneFirewallInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkImmunity"
      | "convictionOf"
      | "getThreatLevel"
      | "intuitionVault"
      | "maliciousVaultIds"
      | "minRegistrationAssets"
      | "minStakeThreshold"
      | "owner"
      | "registerThreat"
      | "renounceOwnership"
      | "setThreshold"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ImmunityCheck"
      | "OwnershipTransferred"
      | "ThreatLinked"
      | "ThresholdUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkImmunity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "convictionOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getThreatLevel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "intuitionVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maliciousVaultIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minRegistrationAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minStakeThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerThreat",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkImmunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convictionOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getThreatLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "intuitionVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maliciousVaultIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minRegistrationAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minStakeThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerThreat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ImmunityCheckEvent {
  export type InputTuple = [
    target: AddressLike,
    isSafe: boolean,
    riskLevel: BigNumberish
  ];
  export type OutputTuple = [
    target: string,
    isSafe: boolean,
    riskLevel: bigint
  ];
  export interface OutputObject {
    target: string;
    isSafe: boolean;
    riskLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThreatLinkedEvent {
  export type InputTuple = [
    suspect: AddressLike,
    tripleId: BigNumberish,
    registrar: AddressLike
  ];
  export type OutputTuple = [
    suspect: string,
    tripleId: bigint,
    registrar: string
  ];
  export interface OutputObject {
    suspect: string;
    tripleId: bigint;
    registrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [newThreshold: BigNumberish];
  export type OutputTuple = [newThreshold: bigint];
  export interface OutputObject {
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ImmuneFirewall extends BaseContract {
  connect(runner?: ContractRunner | null): ImmuneFirewall;
  waitForDeployment(): Promise<this>;

  interface: ImmuneFirewallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkImmunity: TypedContractMethod<
    [_target: AddressLike],
    [boolean],
    "nonpayable"
  >;

  convictionOf: TypedContractMethod<
    [_target: AddressLike],
    [
      [bigint, bigint, bigint] & {
        assets: bigint;
        shares: bigint;
        tripleId: bigint;
      }
    ],
    "view"
  >;

  getThreatLevel: TypedContractMethod<[_target: AddressLike], [bigint], "view">;

  intuitionVault: TypedContractMethod<[], [string], "view">;

  maliciousVaultIds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  minRegistrationAssets: TypedContractMethod<[], [bigint], "view">;

  minStakeThreshold: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerThreat: TypedContractMethod<
    [_suspect: AddressLike, _tripleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setThreshold: TypedContractMethod<
    [_newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkImmunity"
  ): TypedContractMethod<[_target: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "convictionOf"
  ): TypedContractMethod<
    [_target: AddressLike],
    [
      [bigint, bigint, bigint] & {
        assets: bigint;
        shares: bigint;
        tripleId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getThreatLevel"
  ): TypedContractMethod<[_target: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "intuitionVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maliciousVaultIds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "minRegistrationAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minStakeThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerThreat"
  ): TypedContractMethod<
    [_suspect: AddressLike, _tripleId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setThreshold"
  ): TypedContractMethod<[_newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ImmunityCheck"
  ): TypedContractEvent<
    ImmunityCheckEvent.InputTuple,
    ImmunityCheckEvent.OutputTuple,
    ImmunityCheckEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ThreatLinked"
  ): TypedContractEvent<
    ThreatLinkedEvent.InputTuple,
    ThreatLinkedEvent.OutputTuple,
    ThreatLinkedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;

  filters: {
    "ImmunityCheck(address,bool,uint256)": TypedContractEvent<
      ImmunityCheckEvent.InputTuple,
      ImmunityCheckEvent.OutputTuple,
      ImmunityCheckEvent.OutputObject
    >;
    ImmunityCheck: TypedContractEvent<
      ImmunityCheckEvent.InputTuple,
      ImmunityCheckEvent.OutputTuple,
      ImmunityCheckEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ThreatLinked(address,uint256,address)": TypedContractEvent<
      ThreatLinkedEvent.InputTuple,
      ThreatLinkedEvent.OutputTuple,
      ThreatLinkedEvent.OutputObject
    >;
    ThreatLinked: TypedContractEvent<
      ThreatLinkedEvent.InputTuple,
      ThreatLinkedEvent.OutputTuple,
      ThreatLinkedEvent.OutputObject
    >;

    "ThresholdUpdated(uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
  };
}
