/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockEthMultiVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getTripleAtoms"
      | "getVaultStateForUser"
      | "isTripleId"
      | "setIsTriple"
      | "setVault"
      | "vaults"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getTripleAtoms",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultStateForUser",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTripleId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setIsTriple",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTripleAtoms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultStateForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isTripleId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIsTriple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
}

export interface MockEthMultiVault extends BaseContract {
  connect(runner?: ContractRunner | null): MockEthMultiVault;
  waitForDeployment(): Promise<this>;

  interface: MockEthMultiVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getTripleAtoms: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;

  getVaultStateForUser: TypedContractMethod<
    [vaultId: BigNumberish, arg1: AddressLike],
    [[bigint, bigint]],
    "view"
  >;

  isTripleId: TypedContractMethod<[id: BigNumberish], [boolean], "view">;

  setIsTriple: TypedContractMethod<
    [vaultId: BigNumberish, value: boolean],
    [void],
    "nonpayable"
  >;

  setVault: TypedContractMethod<
    [vaultId: BigNumberish, assets: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  vaults: TypedContractMethod<
    [vaultId: BigNumberish],
    [[bigint, bigint] & { totalAssets: bigint; totalShares: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getTripleAtoms"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultStateForUser"
  ): TypedContractMethod<
    [vaultId: BigNumberish, arg1: AddressLike],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTripleId"
  ): TypedContractMethod<[id: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "setIsTriple"
  ): TypedContractMethod<
    [vaultId: BigNumberish, value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<
    [vaultId: BigNumberish, assets: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [[bigint, bigint] & { totalAssets: bigint; totalShares: bigint }],
    "view"
  >;

  filters: {};
}
