/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iIntuitionMultiVaultSol from "./IIntuitionMultiVault.sol";
export type { iIntuitionMultiVaultSol };
