/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEthMultiVault,
  IEthMultiVaultInterface,
} from "../../../../contracts/interfaces/IIntuitionMultiVault.sol/IEthMultiVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getTripleAtoms",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "termId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "curveId",
        type: "uint256",
      },
    ],
    name: "getVault",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAssets",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalShares",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "getVaultStateForUser",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "termId",
        type: "bytes32",
      },
    ],
    name: "isTriple",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEthMultiVault__factory {
  static readonly abi = _abi;
  static createInterface(): IEthMultiVaultInterface {
    return new Interface(_abi) as IEthMultiVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEthMultiVault {
    return new Contract(address, _abi, runner) as unknown as IEthMultiVault;
  }
}
