/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockEthMultiVault,
  MockEthMultiVaultInterface,
} from "../../contracts/MockEthMultiVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getTripleAtoms",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "getVaultStateForUser",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "isTripleId",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "value",
        type: "bool",
      },
    ],
    name: "setIsTriple",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "setVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
    ],
    name: "vaults",
    outputs: [
      {
        internalType: "uint256",
        name: "totalAssets",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalShares",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610342806100206000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c80630cde801b1461006757806366e34a33146100a1578063876f5da4146100c457806389065256146100f45780638c64ea4a14610146578063d29442b914610181575b600080fd5b610081610075366004610218565b50600190600290600390565b604080519384526020840192909252908201526060015b60405180910390f35b6100b46100af366004610218565b6101bc565b6040519015158152602001610098565b6100f26100d2366004610231565b600091825260016020526040909120805460ff1916911515919091179055565b005b610131610102366004610266565b506000908152602081815260409182902082518084019093528054808452600190910154929091018290529091565b60408051928352602083019190915201610098565b610131610154366004610218565b60009081526020818152604091829020825180840190935280548084526001909101549290910182905291565b6100f261018f366004610297565b60408051808201825292835260208084019283526000948552849052909220905181559051600190910155565b6000806101cc60026000196102c3565b83119050806101ec5760008381526001602052604090205460ff16610211565b600160006101fc856000196102e5565b815260208101919091526040016000205460ff165b9392505050565b60006020828403121561022a57600080fd5b5035919050565b6000806040838503121561024457600080fd5b823591506020830135801515811461025b57600080fd5b809150509250929050565b6000806040838503121561027957600080fd5b8235915060208301356001600160a01b038116811461025b57600080fd5b6000806000606084860312156102ac57600080fd5b505081359360208301359350604090920135919050565b6000826102e057634e487b7160e01b600052601260045260246000fd5b500490565b8181038181111561030657634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220b61363d4b28278936c3d40dd13a13a65db7ae94057f0d6d2a70d3343d7b3bed964736f6c63430008150033";

type MockEthMultiVaultConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockEthMultiVaultConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockEthMultiVault__factory extends ContractFactory {
  constructor(...args: MockEthMultiVaultConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockEthMultiVault & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockEthMultiVault__factory {
    return super.connect(runner) as MockEthMultiVault__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockEthMultiVaultInterface {
    return new Interface(_abi) as MockEthMultiVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockEthMultiVault {
    return new Contract(address, _abi, runner) as unknown as MockEthMultiVault;
  }
}
