/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IEthMultiVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getTripleAtoms"
      | "getVault"
      | "getVaultStateForUser"
      | "isTriple"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getTripleAtoms",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultStateForUser",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isTriple", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "getTripleAtoms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultStateForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isTriple", data: BytesLike): Result;
}

export interface IEthMultiVault extends BaseContract {
  connect(runner?: ContractRunner | null): IEthMultiVault;
  waitForDeployment(): Promise<this>;

  interface: IEthMultiVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getTripleAtoms: TypedContractMethod<
    [id: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;

  getVault: TypedContractMethod<
    [termId: BytesLike, curveId: BigNumberish],
    [[bigint, bigint] & { totalAssets: bigint; totalShares: bigint }],
    "view"
  >;

  getVaultStateForUser: TypedContractMethod<
    [vaultId: BigNumberish, receiver: AddressLike],
    [[bigint, bigint]],
    "view"
  >;

  isTriple: TypedContractMethod<[termId: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getTripleAtoms"
  ): TypedContractMethod<
    [id: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [termId: BytesLike, curveId: BigNumberish],
    [[bigint, bigint] & { totalAssets: bigint; totalShares: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultStateForUser"
  ): TypedContractMethod<
    [vaultId: BigNumberish, receiver: AddressLike],
    [[bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTriple"
  ): TypedContractMethod<[termId: BytesLike], [boolean], "view">;

  filters: {};
}
